# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrKl-JuQMcdMGYTNJd5L1zWu2GrjNwj5
"""

!whisper "Novo áudio.mp3" --model medium

